# Generated by Django 5.2.8 on 2025-11-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Attack Title', max_length=200)),
                ('prompt', models.TextField(help_text='User prompt')),
                ('target_info', models.TextField(blank=True, help_text='Target Context (RAG)', null=True)),
                ('generated_content', models.TextField(blank=True, help_text='Generated Content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefenseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, help_text='File name', max_length=255, null=True)),
                ('content_extracted', models.TextField(help_text='Extracted Content')),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('analysis_report', models.TextField(blank=True, help_text='LLM detailed report analysis', null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
