# Generated by Django 5.2.8 on 2025-11-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenseanalysis',
            name='input_file',
            field=models.FileField(blank=True, help_text='Document for Analysis', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='defenseanalysis',
            name='content_extracted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defenseanalysis',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
